### ISSUE TITLE
[Gnome-724386] Error Setting Permissions: Operation not permitted during import and new version creation

### ISSUE THREAD

**Issue by NguyenMatthieu** [mono/f-spot#19] opened 2014-07-22 14:48 UTC
cf. Gnome Bugzilla's https://bugzilla.gnome.org/show_bug.cgi?id=724386

**Comment by dkoeb** [comment] 2016-03-04 19:06
Just to clarify this: "Prerequisite: Pictures are located under an NTFS or FAT partition"

Do you mean source location where you import pictures from is on NTFS/FAT or the target folder where pictures are imported to?

**Comment by NguyenMatthieu** [comment] 2016-03-04 19:27
@dkoeb target folder, as hinted by the Pull Request. GLIBs Copy call will say it can't *set* permissions. It's a problem when writing to a partition like NTFS or FAT, not an Unix one (where Glib is a happy camper)

**Comment by dkoeb** [comment] 2016-03-04 21:26
Are you able reproduce this error? Having a FAT file system as target folder is not enough for reproducing it. I assume that it has to do with the options you used to mount your file systems.
May you share your mount options for those partitions and the owner/group and mode bits of the target folder?

**Comment by NguyenMatthieu** [comment] 2016-03-05 09:41
@dkoeb I'm also suspecting it could be solved via some fstab magic, that's why I told @decriptor on gitter that I still wanted to look at other solutions before it got actually merged

**Comment by dkoeb** [comment] 2016-03-05 13:18
Even if you can solve it with some fstab settings, f-spot should not crash in the first place and handle such problems sanely. I therefore would like to reproduce your setup and see why f-spot crashes and what we can do about it. Your PR logs and swallows the problem by putting a try/catch around. I think we can do better by informing the user of the real problem or even taking some automated actions (e.g., if copying of file attributes is the problem, we may adapt that in case of NTFS/FAT file systems).

**Comment by NguyenMatthieu** [comment] 2016-04-01 14:43
@dkoeb OK. I just tried again with the absolute latest version of f-spot, fresh from the git repo. And the error seems gone. I'm not sure if there's been an update in GLib, or a change in my distro's fstab or what, but I can't reproduce anymore...

**Comment by decriptor** [comment] 2016-04-01 15:14
@NguyenMatthieu that's good news!

**Comment by dkoeb** [comment] 2016-04-01 18:21
I don't think the actual copying code has changed, so we might still run into this issue again. But since we can't reproduce it I suggest to close this issue and wait until it turns up again.
This makes pull request [#18](https://github.com/mono/f-spot/pull/18) obsolete as well, right?

**Comment by decriptor** [comment] 2016-04-01 20:19
I agree. Let's close this report, however, I think might leave the PR open because we could probably be doing a better job with error handling.

**Closed by decriptor** 2016-04-01 20:19 UTC
