### ISSUE TITLE
repeatable crash - possibly due to specific photo

### ISSUE THREAD

**Issue by genterminl** [mono/f-spot#114] opened 2017-12-10 01:16 UTC
I've been trying to track down a crash importing photos, but I found every time I try to scoll to a specific date range, I get what seems to be the same crash.  If I'm in browse view, it doesn't matter if I use the scroll bar, the mouse wheel, or up- or down-arrow to get the the offending date or image.  In filmstip view, it also crashes when I get to near a particular image/date.  I can select from the time-line either before or after, but if I select the right time - crash.
The following is one line I've seen repeatedly, which seems really strange to me, and I hope will help track this down:
System.Exception: Something is horribly wrong, this should never happen: no default version!

[scroll_crash.txt](https://github.com/mono/f-spot/files/1545247/scroll_crash.txt)
[scroll_crash2.txt](https://github.com/mono/f-spot/files/1545248/scroll_crash2.txt)

Note I've looked at every image within the area that causes the crash, and I don't see anything special about any one of them.

**Comment by dkoeb** [comment] 2017-12-10 11:25
That's the same error as in issue #112. It seems that some bug  - probably on importing photos - results in a corrupted database. You should be able to identify the image with this sql query:

`select * from photos outer left join photo_versions on photos.id = photo_versions.photo_id and photos.default_version_id = photo_versions.version_id;`

http://sqlitebrowser.org/ is a nice tool to work with sqlite databases. You should also make a backup of your f-spot database (~/.config/f-spot/photos.db).

**Comment by dkoeb** [comment] 2017-12-10 13:55
The sql query is missing a where clause:

`select * from photos outer left join photo_versions on photos.id = photo_versions.photo_id and photos.default_version_id = photo_versions.version_id where photo_id is null;`

**Comment by dkoeb** [comment] 2017-12-10 19:20
Every photo in the db has a list of photo versions assigned to it. If no photo version exists (not even a single one) you will see this exception. So for some reason the photo with id 5403 has a version_id set that does not exist.

Search for a row in photo_versions table that has photo_id = 5403. If that exists, set default_version_id in photos table of photo with id 5403 to the version_id of that row in photo_versions.
If none exists either delete the row with id = 5403 in photos or create an entry in photo_versions on your own.

**Comment by dkoeb** [comment] 2017-12-10 19:21
If you happen to have some stack traces of exceptions that occured on import then please post them here. They might include the line of code that caused this issue.

**Comment by genterminl** [comment] 2017-12-10 19:46
[error.txt](https://github.com/mono/f-spot/files/1546011/error.txt)
This has a bunch of imports which ended in the crash.  Hopefully they point to the culprit.

**Comment by dkoeb** [comment] 2017-12-11 21:32
Unfortunately the log doesn't help. The root cause exceptions seem to occur in a background thread and we only see the unhandled-exception exception. Maybe we can add some code to log the unhandled exception stack trace as well...

**Comment by genterminl** [comment] 2017-12-11 22:07
Would it be possible (and useful) to run under gdb?  I've had no luck getting mono-develop installed on my Gentoo box, but maybe I can try on my Win7 laptop.  Would that be at all useful?  (I have no idea if I would still get the crashes on the Win7 box, however.)  Is this crash that spurious that only a few users seem to get bit by it?

**Comment by dkoeb** [comment] 2017-12-17 13:36
PR #115 fixes the bug that causes the exception (and crash) on import. This will prevent new inconsistencies in the database. The already introduced inconsistencies in the database can not be fixed this way and need to be fixed manually.

**Comment by genterminl** [comment] 2017-12-17 20:56
I just did three imports with 118, 157, and 323 photos, with no crash.  I think you got it!  If I can, I'll close this issue as resolved.

**Closed** 2017-12-17 20:57 UTC
